import { avatarForProductName, type PowerAvatarKey } from "./power-avatars"

/** Editorial copy only: never changes merchant descriptions, prices, stock or origins.
 * Season = indicative consumption peak, not the origin or harvest date of a lot.
 * Reference consulted 2026-10-06: Interfel / CTIFL consumption calendars:
 * https://www.lesfruitsetlegumesfrais.com/calendrier-consommation
 * https://www.lesfruitsetlegumesfrais.com/calendrier-consommation?type=fruits
 * No fixed dates are asserted for products without a reliable shared calendar.
 */
type ProduceNote = { comment: string; season: string }
const note = (comment: string, season = "Variable selon les récoltes"): ProduceNote => ({ comment, season })

export const POWER_PRODUCE_NOTES: Record<PowerAvatarKey, ProduceNote> = {
  mangue: note("Une chair fondante et un parfum généreux.", "Octobre à mai"),
  fraise: note("Une petite douceur rouge, parfumée et juteuse.", "Mars à juin"),
  ananas: note("Juteux et acidulé, il réveille les papilles.", "Décembre à mai"),
  tomate: note("Juteuse et savoureuse, à croquer ou à cuisiner.", "Avril à août"),
  banane: note("Douce et moelleuse, parfaite pour le goûter."),
  pomme: note("Le plaisir de croquer, nature ou en compote.", "Octobre à mai"),
  poire: note("Une chair délicate, douce et parfumée.", "Septembre à avril"),
  orange: note("Des quartiers juteux et une touche acidulée.", "Novembre à mai"),
  citron: note("Une pointe d’acidité pour relever vos recettes.", "Décembre à mai"),
  "citron-vert": note("Un petit agrume au parfum vif et frais.", "Décembre à mai"),
  clementine: note("Des quartiers tout doux, faciles à savourer.", "Novembre à mars"),
  pamplemousse: note("Juteux et acidulé, avec une légère amertume.", "Novembre à mai"),
  mandarine: note("Un agrume doux au parfum bien marqué.", "Novembre à mars"),
  kiwi: note("Une chair tendre qui mêle douceur et acidité.", "Novembre à mai"),
  pasteque: note("Croquante et très juteuse, à partager bien fraîche.", "Mai à août"),
  melon: note("Une chair parfumée pour les envies de fraîcheur.", "Juin à septembre"),
  raisin: note("De petites billes juteuses à picorer.", "Août à novembre"),
  cerise: note("Une bouchée gourmande autour de son noyau.", "Mai à juillet"),
  abricot: note("Une peau veloutée et une chair douce et acidulée.", "Mai à août"),
  peche: note("Veloutée et juteuse, avec un parfum délicat.", "Juin à septembre"),
  nectarine: note("Une peau lisse et une chair généreuse en jus.", "Juin à septembre"),
  prune: note("Douce ou acidulée, délicieuse en tarte.", "Juillet à octobre"),
  framboise: note("Une baie délicate au parfum intense.", "Avril à août"),
  mure: note("Une baie sombre, douce et légèrement acidulée.", "Avril à août"),
  myrtille: note("Une petite baie bleue à savourer ou à pâtisser.", "Avril à août"),
  groseille: note("Des petites perles acidulées pour les desserts.", "Avril à août"),
  cassis: note("Une petite baie noire au caractère bien affirmé."),
  figue: note("Une chair douce aux petits grains croquants.", "Août à octobre"),
  grenade: note("Des grains croquants qui éclatent en bouche.", "Août à février"),
  kaki: note("Une chair orangée à savourer à bonne maturité.", "Octobre à janvier"),
  passion: note("Un parfum puissant et une pulpe acidulée.", "Décembre à mai"),
  "noix-de-coco": note("Une chair blanche au goût délicatement exotique."),
  papaye: note("Une chair tendre et douce, à découvrir en dessert."),
  pitaya: note("Une chair douce parsemée de petits grains."),
  litchi: note("Sous sa coque, une chair juteuse et parfumée.", "Décembre à janvier"),
  goyave: note("Un parfum généreux pour vos salades de fruits."),
  carambole: note("Des tranches en étoile pour égayer l’assiette."),
  ramboutan: note("Un fruit à la drôle de coque, à découvrir pelé."),
  mangoustan: note("Une épaisse coque cache des quartiers délicats."),
  durian: note("Un fruit exotique pour les amateurs de découvertes."),
  corossol: note("Une chair blanche à découvrir dans vos desserts."),
  cherimole: note("Une chair crémeuse à savourer à la cuillère."),
  tamarin: note("Une pulpe acidulée pour donner du caractère."),
  kumquat: note("Un petit agrume au contraste doux et acidulé."),
  physalis: note("Une petite baie dorée dans son écrin de feuilles."),
  datte: note("Une bouchée douce et généreuse pour la pause.", "Octobre à mai"),
  avocat: note("Une chair onctueuse pour vos tartines et salades.", "Mars à juillet"),
  jacquier: note("Un grand fruit exotique à découvrir en cuisine."),
  longane: note("Un petit fruit à peler pour découvrir sa chair."),
  nefle: note("Un fruit délicat qui mérite d’être découvert."),
  carotte: note("Croquante crue, fondante une fois cuisinée.", "Octobre à avril"),
  courgette: note("Une saveur douce, en poêlée ou en gratin.", "Mars à septembre"),
  aubergine: note("Une chair fondante après une cuisson soignée.", "Mai à septembre"),
  concombre: note("Du croquant et de la fraîcheur dans les salades.", "Avril à août"),
  poivron: note("Coloré et parfumé, cru ou rôti au four.", "Avril à août"),
  brocoli: note("De petits bouquets à cuire tout simplement.", "Octobre à mai"),
  "chou-fleur": note("Des fleurettes tendres, en gratin ou à croquer.", "Octobre à mars"),
  "chou-rouge": note("Du croquant et de la couleur dans l’assiette.", "Octobre à mars"),
  salade: note("Des feuilles fraîches pour une salade toute simple.", "Toute l’année"),
  epinard: note("Des feuilles tendres à savourer crues ou cuites.", "Octobre à mai"),
  poireau: note("Doux après cuisson, délicieux en fondue.", "Octobre à mars"),
  "celeri-branche": note("Des tiges croquantes au parfum bien marqué.", "Octobre à avril"),
  fenouil: note("Un croquant délicat et une touche anisée.", "Octobre à mai"),
  artichaut: note("Des feuilles à effeuiller et un cœur tendre.", "Février à juin"),
  asperge: note("Une saveur délicate à apprécier simplement.", "Mars à juin"),
  "haricot-vert": note("Fin et tendre, un classique des petits plats.", "Juin à octobre"),
  "petit-pois": note("De petites billes tendres et légèrement sucrées.", "Avril à juillet"),
  radis: note("Une bouchée croquante, parfois un peu piquante.", "Mars à juillet"),
  betterave: note("Une saveur douce et une belle couleur pourpre.", "Toute l’année"),
  navet: note("Doux une fois cuit, il aime les plats mijotés.", "Octobre à mars"),
  panais: note("Une racine douce pour des purées parfumées.", "Novembre à avril"),
  "pomme-de-terre": note("Au four, en purée ou vapeur : à chacun son envie."),
  "patate-douce": note("Fondante et douce, délicieuse rôtie au four.", "Septembre à mai"),
  potiron: note("Une chair douce, parfaite pour un velouté.", "Octobre à février"),
  butternut: note("Une courge fondante pour vos recettes au four.", "Octobre à février"),
  champignon: note("Une saveur délicate, à poêler ou à farcir.", "Octobre à mai"),
  oignon: note("Le petit indispensable pour donner du goût.", "Août à mai"),
  ail: note("Quelques éclats pour parfumer vos petits plats.", "Toute l’année"),
  echalote: note("Un parfum fin pour les sauces et vinaigrettes.", "Août à mai"),
  endive: note("Croquante ou fondante, avec une légère amertume.", "Octobre à avril"),
  basilic: note("Un parfum généreux qui accompagne la tomate."),
  menthe: note("Une touche de fraîcheur dans les plats et boissons."),
  persil: note("Quelques feuilles pour réveiller l’assiette.", "Toute l’année"),
  coriandre: note("Un parfum bien affirmé pour les plats relevés."),
  ciboulette: note("De fines tiges à ciseler sur vos recettes."),
  thym: note("Quelques brins pour parfumer les cuissons."),
  romarin: note("Un parfum intense pour les plats rôtis."),
  sauge: note("Des feuilles aromatiques pour une cuisine parfumée."),
  estragon: note("Une touche anisée dans les sauces et salades."),
  aneth: note("Un parfum léger pour les sauces et crudités."),
  laurier: note("Une feuille pour parfumer les plats mijotés."),
  origan: note("Une touche aromatique sur les tomates et pizzas."),
  sarriette: note("Un parfum soutenu pour relever les légumes."),
  cerfeuil: note("Des feuilles délicates à ajouter en fin de recette."),
  melisse: note("Un parfum citronné pour une touche de fraîcheur."),
  verveine: note("Des feuilles parfumées à découvrir en infusion."),
  oseille: note("Une note acidulée dans les sauces et soupes."),
  gingembre: note("Une note vive et piquante dans vos recettes."),
  curcuma: note("De la couleur et une touche épicée en cuisine."),
  citronnelle: note("Un parfum citronné pour les bouillons et sauces."),
}

export function produceNoteForName(name: string) {
  const avatar = avatarForProductName(name)
  return avatar ? POWER_PRODUCE_NOTES[avatar.key] : null
}
